### ISSUE TITLE
Superfluous volume assignment in database_default

### ISSUE THREAD

**Issue by MacLake** [django-cms/django-cms-quickstart#50]
The [volume assignment](https://github.com/django-cms/django-cms-quickstart/blob/main/docker-compose.yml#L37) in the `database_default`section doesn’t make sense.  It doesn’t break anything, but it’s not good for anything either.

```yaml
  database_default:
  # …
    volumes:
       - postgres-data:/var/lib/postgresql/data/
```
